FROM openjdk:17-jdk-alpine
LABEL authors="ghassendallegi"
EXPOSE 8092
ADD target/ReservationMS-0.0.1-SNAPSHOT.jar ReservationMS-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/ReservationMS-0.0.1-SNAPSHOT.jar"]
