name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-deploy:
    name: SonarCloud + Deploy Nexus
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      - name: Build and analyze with SonarCloud
        working-directory: ServiceMS
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn clean verify sonar:sonar -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Deploy JAR to Nexus
        working-directory: ServiceMS
        env:
          MAVEN_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        run: |
          mvn deploy -DskipTests -DaltDeploymentRepository=nexus::default::${{ secrets.NEXUS_URL }} \
            -Dusername=$MAVEN_USERNAME -Dpassword=$MAVEN_PASSWORD

      - name: Build Docker image
        working-directory: ServiceMS
        run: |
          docker build -t myapp:latest .

      - name: Log in to Nexus Docker Registry
        run: |
          echo "${{ secrets.NEXUS_PASSWORD }}" | docker login ${{ secrets.NEXUS_DOCKER_REGISTRY }} -u ${{ secrets.NEXUS_USERNAME }} --password-stdin

      - name: Tag Docker image
        run: |
          docker tag myapp:latest ${{ secrets.NEXUS_DOCKER_REGISTRY }}/myapp:latest

      - name: Push Docker image to Nexus
        run: |
          docker push ${{ secrets.NEXUS_DOCKER_REGISTRY }}/myapp:latest
